### PR TITLE
Add missing setters for structs

### PR DESCRIPTION
**Pull request by TristanCacqueray**
This change adds setters for struct already having global getters.

Related to #77

### CODE REVIEW

**Comment by TristanCacqueray** [comment]
@saschagrunert the new commit should add a set forall get/get_copy

**Comment by cgwalters** [comment]
FYI I tried this and it works well for what I need (append a layer to a manifest).  Would be good to get a new release queued.

**Comment by utam0k** [comment]
> FYI I tried this and it works well for what I need (append a layer to a manifest). Would be good to get a new release queued.

Good, I'm sorry for the inconvenience.

**Comment by utam0k** [comment]
@saschagrunert  Would you like to release? Is there something blocking the release?

**Comment by saschagrunert** [comment]
> @saschagrunert Would you like to release? Is there something blocking the release?

Thanks for taking care of the release while I was OOO! :green_heart:

**Pull request merged**
